# docker build -f docker/Dockerfile-neuralangelo -t chenhsuanlin/neuralangelo:23.04-py3 .
# docker push chenhsuanlin/neuralangelo:23.04-py3

FROM nvcr.io/nvidia/pytorch:23.04-py3
ARG DEBIAN_FRONTEND=noninteractive

# Install basics
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    bzip2 \
    ca-certificates \
    cmake \
    curl \
    ffmpeg \
    g++ \
    git \
    libx264-dev \
    tmux \
    wget

# Update pip
RUN pip install --upgrade pip

# Code formatting
RUN pip install --upgrade \
    flake8 \
    pre-commit

# Install base Python libraries for Imaginaire
COPY requirements.txt requirements.txt
ARG FORCE_CUDA=1
ARG TCNN_CUDA_ARCHITECTURES=70,72,75,80,86
RUN pip install --upgrade -r requirements.txt
