# -----------------------------------------------------------------------------
# Copyright (c) 2023, NVIDIA CORPORATION. All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto. Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
# -----------------------------------------------------------------------------

# NOTE: this template is an example for designing your custom config file. It is not intended to be used directly.
# Please preprocess your custom data and auto-generate the config file before customizing.

_parent_: projects/neuralangelo/configs/base.yaml

model:
    object:
        sdf:
            mlp:
                inside_out: False
            encoding:
                coarse2fine:
                    init_active_level: 8
    appear_embed:
        enabled: True
        dim: 8

data:
    type: projects.neuralangelo.data
    root:  # The root path of the dataset.
    num_images:  # The number of training images.
    train:
        image_size: [1200,1600]
        batch_size: 1
        subset:
    val:
        image_size: [300,400]
        batch_size: 1
        subset: 1
        max_viz_samples:
    readjust:
        center: [0.,0.,0.]
        scale: 1.
